### ISSUE TITLE
Duplicate freezes game

### ISSUE THREAD

**Issue by ziolek666** [jcbantuelle/dominion-meteor#13]
After having one duplicate on tavern mat and then playing 2nd and 3rd duplicate and after that buying gold and calling duplicate from the tavern mat game froze (can't finish turn) on 3rd duplicate. Server log:

```
Exception in callback of async function: TypeError: Cannot read property 'type_class' of undefined  
  at Function.render (app/game/server/view_objects/card_view.js:10:33)  
  at gain_copy (app/cards/adventures/duplicate.js:42:81)  
  at app/game/server/services/turn_event_processor.js:20:7
```

Also it would be nice to have the "Destroy Game" button back for situations like this ;-)

BTW Great work! Brings back memories from isotropic ;) Thanks!

**Comment by jcbantuelle** [comment]
Thanks for the feedback and good catch. I'm glad you're enjoying the game! I've just pushed a fix for this issue.

Regarding the destroy game button, when I have an issue with a live server and a game gets locked, I typically just restart the server. The destroy button feature was a hamfisted approach that clobbered more than you'd want on a live system. I think an excellent feature to add would be a "forfeit" button, and "offer draw" button, instead of the destroy game button.

I do still have the destroy game button available in the `testing` branch if you wanted to pull that into your own local copy for gameplay too.
