### ISSUE TITLE
Peddler's price isn't changing dinamically

### ISSUE THREAD

**Issue by michalbe** [jcbantuelle/dominion-meteor#31]
It always shows `$8`, no matter how many action cards are in play.

**Comment by jcbantuelle** [comment]
Closed by 683a5bd5a0d5b35681c690a85fb8e1a543d5a5a8

The discount doesn't take effect until the buy phase, so actions don't automatically reduce the price. Any actions that would trigger a gain based on cost will consider Peddler to cost $8 for example. If you have multiple buys, it would show the discounted cost after the first one was clicked on, as that pushes the game state over into the buy phase.

There was a related bug however, which is that while the game internally tracks playing treasures as a separate phase (because you can only play treasures before you purchase a card), technically the game considers playing treasures as part of the buy phase. I've updated the code to reflect this Peddler price adjustment once a treasure has been played.

**Comment by michalbe** [comment]
Awesome, thanks for rapid response. 



There's a PR awaiting review [here](https://github.com/jcbantuelle/dominion-meteor/pull/30), just saying :).

**Comment by jcbantuelle** [comment]
Yep, I've got it on my list of things to do to give it a review. Since it's a much larger set of code changes it's going to take me longer to work through, while this was very low hanging fruit.
